// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe01ZuOuyCHYdwB4oK-x_3pI6hBGA62U4',
    appId: '1:147610163285:web:bc70bd697fe1524d981cdc',
    messagingSenderId: '147610163285',
    projectId: 'peto-2',
    authDomain: 'peto-2.firebaseapp.com',
    storageBucket: 'peto-2.appspot.com',
    measurementId: 'G-Z9VY5X4CB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zhzgdQ_d8uT2YSHhyGax-gWMD77Ietc',
    appId: '1:147610163285:android:1c99019f9683222a981cdc',
    messagingSenderId: '147610163285',
    projectId: 'peto-2',
    storageBucket: 'peto-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChD5zr7NWiWC4Z1VRQGDKy4gOIsOZRvcA',
    appId: '1:147610163285:ios:1727107362cd9d80981cdc',
    messagingSenderId: '147610163285',
    projectId: 'peto-2',
    storageBucket: 'peto-2.appspot.com',
    iosClientId:
        '147610163285-b8jeif2vspvfip14i7eap9volltn64d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.peto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChD5zr7NWiWC4Z1VRQGDKy4gOIsOZRvcA',
    appId: '1:147610163285:ios:8fca6836a08a635b981cdc',
    messagingSenderId: '147610163285',
    projectId: 'peto-2',
    storageBucket: 'peto-2.appspot.com',
    iosClientId:
        '147610163285-f4umhuth77hk422rlg0vmvukiml3h8o0.apps.googleusercontent.com',
    iosBundleId: 'com.example.peto.RunnerTests',
  );
}
